package main

// The UI contract is an adapter boundary, not a replacement for member contracts.
// Its independent decoder and observed command outcome decide whether work can
// continue; an authored capability declaration does not establish conformance.
const taskHandoffInstructions = `
Implement the UI team handoff contract documented in interfaces/hire/TASK-HANDOFF.md. Declare task-runtime.json with exactly {"version":2,"resume":true,"local_only":true}; version 1 does not provide the required outcome contract. Keep the selected team's native entry and member contracts behind bin/task.

For each invocation atomically write BENCH_TASK_WORK/task-result.json with exactly: version (1), invocation (BENCH_TASK_INVOCATION), goal_sha256 (BENCH_TASK_GOAL_SHA256), definition_sha256 (BENCH_TASK_DEFINITION_SHA256), status (complete|continue|blocked|needs_input), stage, message, reason, next, question, files. Strings are plain text: stage at most 120 characters, message/reason/next at most 2000 each, question at most 1000. Report at most 64 KiB; manifest at most 64 files, 25 MiB each and 100 MiB total. At most 32 deliverables with distinct supported-format basenames; use editable archives for nested source. files is an array of exact {"path":"relative/file","kind":"work|evidence|deliverable","sha256":"lowercase SHA256"} objects naming existing regular files under BENCH_TASK_WORK, without symlink components. Bind the current invocation, never reuse an earlier report. Complete requires exit 0 and empty reason/next/question. Continue requires observed 0 or 2, concrete next work and empty reason/question. Blocked requires reason and next, an empty question, and may describe any observed exit without authorizing replay. Needs_input requires observed 0/2/75, a genuinely missing user fact in question and empty reason/next. Preserve exact other command outcomes and never claim completion or resume eligibility after failure, interruption or uncertainty. The controller independently validates and snapshots this report before review; missing or stale reports stop the handoff.

Expose partial source as work files and bounded member reports/check receipts as evidence even when acceptance fails. Reserve deliverable for outputs offered to the user. Work files track content progress: do not use transcripts, timestamps, request text, handoff summaries or receipts as progress. A structurally valid member report can say blocked even when Agent/check exits 0. Translate that status and its concrete blockers; do not replace it with a generic unfinished exit or erase the partial work. Reviewability is separate from release readiness: route an existing candidate to its independent reviewer when that review is the remaining authorized work, while preserving unrelated external blockers and without declaring the package accepted.

Write each member's durable started receipt BEFORE launching its public command, then record its observed exact outcome. Bind the full definition (including checks and executable modes), selected inputs, checkpoint and accepted output hashes. Missing or started-only receipts and interrupted/unknown outcomes cannot be replayed. Validate durable attempt history before every reuse, correction or accepted-review decision: require contiguous attempt records and a latest receipt matching the newest record. A missing pointer, a stale successful pointer hiding a newer started attempt, or contradictory history is unknown, never first use; stop without launching any member. With BENCH_TASK_RESUME=1 retain workspace, explicit checkpoint from the first invocation and original edit baseline; resume only observed 0/2 with a specific authorized correction. Use Agent -B when correction requires action despite a passing precheck. Reuse accepted unaffected outputs only after checking all bindings. Changed producer outputs invalidate downstream review; stage the current request, complete selected source and its supporting evidence together. Never require a producer to claim independent review before allowing that review to run. This local continuation grants no external actions.

Before completing authoring, exercise bin/task through offline executable fixtures with stub public member commands and real member-shaped outputs: partial 2 then completion; valid blocked report with exit 0; a correction despite passing precheck; changed producer bytes invalidating review; unchanged source with changed prose/receipt timestamps; missing capability returning a concrete blocker; stale request/input/definition/output hashes; unknown/130 outcomes; termination after started receipt but before an observed result; and deleted/stale latest receipts while attempt history remains. Assert exact outcomes, no unsafe replay, retained partial work, current report bindings, and original-design preservation. These tests exercise wiring only, not specialist quality; neither the declaration nor an author-written passing report replaces independent controller validation. Do not run live models in authoring fixtures.
`
