"""Verified, reversible user-prefix installation of independent tool packages."""

import argparse
from contextlib import contextmanager
import fcntl
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import re
import shlex
import shutil
import stat
import subprocess
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[1]
NAME = re.compile(r"^[a-z][a-z0-9-]*$")
DRAFT_REFERENCE = "skills/draft/references/tools.md"


class InstallError(ValueError):
    pass


class RecoveryError(InstallError):
    pass


def digest(path):
    value = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            value.update(chunk)
    return value.hexdigest()


def valid_name(value):
    return isinstance(value, str) and NAME.fullmatch(value) is not None


def read_json(path):
    if path.is_symlink() or not path.is_file():
        raise InstallError(f"expected a regular file: {path}")
    try:
        return json.loads(path.read_text())
    except (UnicodeError, json.JSONDecodeError) as error:
        raise InstallError(f"invalid JSON in {path}: {error}") from error


def relative_path(value):
    if not isinstance(value, str):
        raise InstallError("package file paths must be strings")
    path = PurePosixPath(value)
    if not value or path.is_absolute() or str(path) != value or any(
        part in (".", "..") for part in path.parts
    ) or "\\" in value or "\x00" in value:
        raise InstallError(f"unsafe package path: {value!r}")
    return path


def mode_bits(value):
    try:
        bits = int(value, 8) if isinstance(value, str) else value
    except ValueError as error:
        raise InstallError(f"invalid file mode: {value!r}") from error
    if type(bits) is not int or bits < 0 or bits > 0o777:
        raise InstallError(f"invalid file mode: {value!r}")
    return bits


def inventory(directory):
    result = set()
    for base, directories, files in os.walk(directory, followlinks=False):
        parent = Path(base)
        for name in list(directories):
            path = parent / name
            if path.is_symlink():
                result.add(path.relative_to(directory).as_posix())
                directories.remove(name)
        for name in files:
            result.add((parent / name).relative_to(directory).as_posix())
    return result - {"package.json"}


def verify_package(directory, name, installed=False):
    """Check every payload file; only installed Draft's generated bytes may vary."""
    if directory.is_symlink() or not directory.is_dir():
        raise InstallError(f"expected a real package directory: {directory}")
    receipt = read_json(directory / "package.json")
    if not isinstance(receipt, dict) or receipt.get("schema") != 1 or receipt.get("name") != name:
        raise InstallError(f"invalid package identity in {directory}")
    commands = receipt.get("commands")
    if not isinstance(commands, list) or not commands or not all(map(valid_name, commands)) or len(commands) != len(set(commands)):
        raise InstallError(f"invalid command inventory in {directory}")
    mutable = receipt.get("mutable_paths", [])
    if mutable not in ([], [DRAFT_REFERENCE]) or (mutable and name != "draft"):
        raise InstallError(f"unsupported mutable paths in {directory}")
    records = receipt.get("files")
    if not isinstance(records, list) or not records:
        raise InstallError(f"missing file inventory in {directory}")
    seen = set()
    for record in records:
        if not isinstance(record, dict):
            raise InstallError(f"invalid file record in {directory}")
        relative = str(relative_path(record.get("path")))
        if relative == "package.json" or relative in seen:
            raise InstallError(f"duplicate or reserved package path: {relative}")
        seen.add(relative)
        path = directory / relative
        for parent in path.parents:
            if parent == directory:
                break
            if parent.is_symlink():
                raise InstallError(f"symlink parent in package: {path}")
        if "symlink" in record:
            target = record["symlink"]
            if not isinstance(target, str) or not target or Path(target).is_absolute() or not path.is_symlink() or os.readlink(path) != target:
                raise InstallError(f"invalid package symlink: {path}")
            try:
                resolved = path.resolve(strict=True)
                resolved.relative_to(directory.resolve())
            except (OSError, RuntimeError, ValueError) as error:
                raise InstallError(f"package symlink escapes or has no target: {path}") from error
            if not resolved.is_file() or relative in mutable:
                raise InstallError(f"package symlink must target an internal regular file: {path}")
        else:
            if path.is_symlink() or not path.is_file():
                raise InstallError(f"missing or nonregular package file: {path}")
            actual_mode = stat.S_IMODE(path.stat().st_mode)
            packaged_mode = mode_bits(record.get("mode"))
            mutable_installed = installed and relative in mutable
            # Draft sync creates its reference with the caller's umask. It may
            # restrict packaged read/write permissions, but cannot add authority
            # or remove the owner's ability to read the generated reference.
            allowed_mode = (bool(actual_mode & 0o400) and
                            not (actual_mode & ~packaged_mode) and
                            not (actual_mode & 0o111)) if mutable_installed else actual_mode == packaged_mode
            if not allowed_mode:
                raise InstallError(f"file mode mismatch: {path}")
            expected = record.get("sha256")
            if not isinstance(expected, str) or not re.fullmatch(r"[a-f0-9]{64}", expected):
                raise InstallError(f"invalid file checksum: {path}")
            if not (installed and relative in mutable) and digest(path) != expected:
                raise InstallError(f"file checksum mismatch: {path}")
    actual = inventory(directory)
    if actual != seen:
        raise InstallError(f"package inventory mismatch in {directory}: extra={sorted(actual - seen)}, missing={sorted(seen - actual)}")
    for command in commands:
        path = directory / "bin" / command
        if f"bin/{command}" not in seen or not path.is_file() or not os.access(path, os.X_OK):
            raise InstallError(f"missing executable public command: {path}")
    if not set(mutable).issubset(seen):
        raise InstallError(f"mutable path missing from package: {directory}")
    return receipt


def real_directory(path):
    if path.is_symlink() or (path.exists() and not path.is_dir()):
        raise InstallError(f"refusing a symlink or non-directory install path: {path}")
    path.mkdir(exist_ok=True)


def prepare_prefix(value):
    requested = Path(value).expanduser().absolute()
    if requested.is_symlink():
        raise InstallError(f"install prefix must be a real directory: {requested}")
    prefix = requested.resolve()
    prefix.mkdir(parents=True, exist_ok=True)
    for path in (prefix / "bin", prefix / "lib", prefix / "lib/bench-tools"):
        real_directory(path)
    return prefix


@contextmanager
def locked(managed):
    path = managed / ".lock"
    flags = os.O_CREAT | os.O_RDWR | getattr(os, "O_NOFOLLOW", 0)
    descriptor = os.open(path, flags, 0o600)
    try:
        if not stat.S_ISREG(os.fstat(descriptor).st_mode):
            raise InstallError(f"install lock is not a regular file: {path}")
        try:
            fcntl.flock(descriptor, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError as error:
            raise InstallError(f"another installation is using {managed}") from error
        yield
    finally:
        os.close(descriptor)


def read_state(managed):
    path = managed / "installed.json"
    if not os.path.lexists(path):
        return {"schema": 1, "tools": {}}
    state = read_json(path)
    if not isinstance(state, dict) or state.get("schema") != 1 or not isinstance(state.get("tools"), dict):
        raise InstallError(f"invalid ownership record: {path}")
    commands = set()
    for name, record in state["tools"].items():
        if not valid_name(name) or not isinstance(record, dict):
            raise InstallError(f"invalid owner in {path}")
        checksum, names = record.get("package_sha256"), record.get("commands")
        if not isinstance(checksum, str) or not re.fullmatch(r"[a-f0-9]{64}", checksum) or not isinstance(names, list) or not names or not all(map(valid_name, names)):
            raise InstallError(f"invalid ownership entry for {name}")
        if commands.intersection(names) or len(names) != len(set(names)):
            raise InstallError(f"duplicate command ownership in {path}")
        commands.update(names)
    return state


def command_target(name, command):
    return f"../lib/bench-tools/{name}/bin/{command}"


def verify_owned(prefix, name, record):
    directory = prefix / "lib/bench-tools" / name
    if digest_regular(directory / "package.json") != record["package_sha256"]:
        raise InstallError(f"installed package receipt changed: {directory}")
    receipt = verify_package(directory, name, installed=True)
    if receipt["commands"] != record["commands"]:
        raise InstallError(f"command ownership changed: {name}")
    for command in record["commands"]:
        path = prefix / "bin" / command
        if not path.is_symlink() or os.readlink(path) != command_target(name, command):
            raise InstallError(f"managed command is missing or changed; refusing to replace it: {path}")
    return receipt


def digest_regular(path):
    if path.is_symlink() or not path.is_file():
        raise InstallError(f"expected a regular ownership receipt: {path}")
    return digest(path)


@contextmanager
def staging(managed):
    directory = Path(tempfile.mkdtemp(prefix=".stage-", dir=managed))
    try:
        yield directory
    except RecoveryError:
        # Retain the previous files if an external filesystem failure prevents
        # rollback. A later operation will refuse the inconsistent ownership.
        raise
    except BaseException:
        shutil.rmtree(directory)
        raise
    else:
        shutil.rmtree(directory)


def transact(prefix, sources, remove=()):
    """Commit packages, command links and ownership together; reverse ordinary failures."""
    managed = prefix / "lib/bench-tools"
    with locked(managed):
        state = read_state(managed)
        selected = list(sources) + list(remove)
        old_receipts = {}
        for name in selected:
            if name in state["tools"]:
                old_receipts[name] = verify_owned(prefix, name, state["tools"][name])
            elif os.path.lexists(managed / name):
                raise InstallError(f"refusing unmanaged package directory: {managed / name}")
        receipts = {name: verify_package(source, name) for name, source in sources.items()}
        occupied = {command: name for name, entry in state["tools"].items() for command in entry["commands"]}
        new_commands = {}
        for name, receipt in receipts.items():
            for command in receipt["commands"]:
                path = prefix / "bin" / command
                if command in new_commands or (command in occupied and occupied[command] != name):
                    raise InstallError(f"command belongs to another tool: {command}")
                if os.path.lexists(path) and occupied.get(command) != name:
                    raise InstallError(f"refusing to overwrite unmanaged command: {path}; choose another --prefix or move it yourself")
                new_commands[command] = name
        with staging(managed) as stage:
            (stage / "new").mkdir()
            (stage / "old").mkdir()
            (stage / "links").mkdir()
            updated = json.loads(json.dumps(state))
            for name, source in sources.items():
                destination = stage / "new" / name
                shutil.copytree(source, destination, symlinks=True)
                verify_package(destination, name)
                # Draft generates this reference from installed public commands.
                for relative in old_receipts.get(name, {}).get("mutable_paths", []):
                    if relative in receipts[name].get("mutable_paths", []):
                        shutil.copy2(managed / name / relative, destination / relative)
                if receipts[name].get("mutable_paths"):
                    verify_package(destination, name, installed=True)
                updated["tools"][name] = {
                    "package_sha256": digest(destination / "package.json"),
                    "commands": receipts[name]["commands"],
                }
            for name in remove:
                updated["tools"].pop(name, None)
            (stage / "state.json").write_text(json.dumps(updated, indent=2) + "\n")
            undo = []

            def move(source, destination):
                os.replace(source, destination)
                undo.append(("move", destination, source))

            try:
                for name in selected:
                    if name in state["tools"]:
                        move(managed / name, stage / "old" / name)
                    if name in sources:
                        move(stage / "new" / name, managed / name)
                for name in selected:
                    for command in state["tools"].get(name, {}).get("commands", []):
                        move(prefix / "bin" / command, stage / "links" / command)
                for command, name in new_commands.items():
                    path = prefix / "bin" / command
                    path.symlink_to(command_target(name, command))
                    undo.append(("unlink", path, None))
                if os.path.lexists(managed / "installed.json"):
                    move(managed / "installed.json", stage / "old-state.json")
                move(stage / "state.json", managed / "installed.json")
            except BaseException as failure:
                errors = []
                for operation, source, destination in reversed(undo):
                    try:
                        if operation == "unlink":
                            source.unlink()
                        else:
                            os.replace(source, destination)
                    except OSError as error:
                        errors.append(str(error))
                if errors:
                    raise RecoveryError(f"{failure}; rollback needs repair: {'; '.join(errors)}. Previous files retained in {stage}") from failure
                raise
    return list(sources), list(remove)


def component_names():
    return {entry["name"]: entry for entry in read_json(ROOT / "components.json")["components"]}


def install_main(argv=None):
    parser = argparse.ArgumentParser(description="Build and install independent tools into a user-owned prefix.")
    parser.add_argument("tools", nargs="*", metavar="TOOL", help="components to install (default: all)")
    parser.add_argument("--prefix", default="~/.local", help="installation prefix (default: ~/.local)")
    parser.add_argument("--from-build", type=Path, metavar="DIR", help="install verified packages from DIR without building")
    args = parser.parse_args(argv)
    try:
        components = component_names()
        selected = list(dict.fromkeys(args.tools or components))
        unknown = sorted(set(selected) - set(components))
        if unknown:
            raise InstallError(f"unknown tool(s): {', '.join(unknown)}; available: {', '.join(components)}")
        build = args.from_build.expanduser().resolve() if args.from_build else ROOT / ".build"
        if args.from_build is None:
            subprocess.run([sys.executable, str(ROOT / "scripts/build"), *selected, "--output", str(build)], check=True)
        sources = {name: build / "tools" / name for name in selected}
        for name, source in sources.items():
            if (build / "tools").is_symlink():
                raise InstallError(f"build tools directory must not be a symlink: {build / 'tools'}")
            receipt = verify_package(source, name)
            if receipt["commands"] != [entry["name"] for entry in components[name]["commands"]]:
                raise InstallError(f"package command inventory does not match components.json: {name}")
        prefix = prepare_prefix(args.prefix)
        transact(prefix, sources)
        print(f"Installed {', '.join(selected)} into {prefix}")
        print("Add the commands to this shell:")
        print(f"  export PATH={shlex.quote(str(prefix / 'bin'))}:\"$PATH\"")
        if "draft" in selected:
            print("Make Draft's skill visible to Brief and refresh its generated reference:")
            print(f"  export BRIEF_PATH={shlex.quote(str(prefix / 'lib/bench-tools/draft/skills'))}:"
                  '"${BRIEF_PATH:-.claude/skills:$HOME/.claude/skills:$HOME/.brief/skills}"')
            print("  draft sync")
        return 0
    except (InstallError, OSError, subprocess.CalledProcessError) as error:
        print(f"install: {error}", file=sys.stderr)
        return 1


def uninstall_main(argv=None):
    parser = argparse.ArgumentParser(description="Remove only verified tools owned by this installer.")
    parser.add_argument("tools", nargs="*", metavar="TOOL", help="components to remove (default: all managed tools)")
    parser.add_argument("--prefix", default="~/.local", help="installation prefix (default: ~/.local)")
    args = parser.parse_args(argv)
    try:
        requested = Path(args.prefix).expanduser().absolute()
        if not requested.exists() and not requested.is_symlink():
            print(f"No managed tools installed in {requested}")
            return 0
        prefix = prepare_prefix(args.prefix)
        state = read_state(prefix / "lib/bench-tools")
        selected = list(dict.fromkeys(args.tools or state["tools"]))
        for name in selected:
            if not valid_name(name) or name not in state["tools"]:
                raise InstallError(f"tool is not installed by this installer: {name}")
        if not selected:
            print(f"No managed tools installed in {prefix}")
            return 0
        transact(prefix, {}, remove=selected)
        print(f"Uninstalled {', '.join(selected)} from {prefix}")
        return 0
    except (InstallError, OSError) as error:
        print(f"uninstall: {error}", file=sys.stderr)
        return 1
